[package]
authors = ["Denis Chaplygin <akashihi@gmail.com>"]
edition = "2018"
name = "nmea"
version = "0.1.0"

[dependencies.lexical-core]
version = "0.8.2"
default-features = false
# Can select only desired parsing/writing features.
features = ["parse-integers", "parse-floats"]